### ISSUE TITLE
yoink#isSwapping returns 0 after YoinkPaste_p

### ISSUE THREAD

**Issue by BlueDrink9** [svermeulen/vim-yoink#17]
I wanted to spend only one map on this plugin, so I mapped:

```
    nmap <expr> <leader>p yoink#isSwapping() ? '<plug>(YoinkPostPasteSwapForward)' : '<plug>(YoinkPaste_p)'
    nmap <expr> <leader>P yoink#isSwapping() ? '<plug>(YoinkPostPasteSwapBack)' : '<plug>(YoinkPaste_P)'
```

However, this only ever pastes, it doesn't swap. Manually calling isSwapping echos 0.

Neovim 4.3

**Comment by BlueDrink9** [comment]
The behavior is the same with your suggested mappings and the `ctrlp` workaround.

I suppose what I'm suggesting is that `yoink#startUndoRepeatSwap` should set s:isSwapping.

If that causes other problems, some other variable that is set on a paste operation would be good

**Comment by svermeulen** [comment]
Ah yeah I see what you're trying to do, that's interesting.

I was able to get it working with this:

```
nmap <expr> <leader>p yoink#canSwap() ? '<plug>(YoinkPostPasteSwapBack)' : '<plug>(YoinkPaste_p)'
nmap <expr> <leader>P yoink#canSwap() ? '<plug>(YoinkPostPasteSwapForward)' : '<plug>(YoinkPaste_P)'
```

I added the `canSwap()` method meant to be used instead of the way you were attempting to use `isSwapping()`.  Since in your case you're not interested if the user has actually started swapping

**Comment by BlueDrink9** [comment]
Thanks, that'll do it.
