### ISSUE TITLE
Vim error on entering visual mode

### ISSUE THREAD

**Issue by BlueDrink9** [svermeulen/vim-yoink#20]
Every so often (haven't narrowed it down yet, but new buffers may be more likely? Or recently-opened vim instances with no viminfo for them...) I get the following error constantly repeating when I enter visual mode and try to move.

```
Error detected while processing function yoink#onYank[14]..<SNR>196_addToHi
story:                                                                     
line   16:                                                                 
E684: list index out of range: 1 
```

**Comment by svermeulen** [comment]
I haven't seen this but I can kinda see how this might happen after looking at the code in that method.  I've added a fix that should address this.  Let me know if you see this again after updating.

**Comment by BlueDrink9** [comment]
Thanks, will do

**Comment by svermeulen** [comment]
Oops, I made a mistake in that last commit, but fixed now.  So if you already upgraded, please upgrade again   :)
