### ISSUE TITLE
Idententtaion not honoured while copying. 

### ISSUE THREAD

**Issue by TanishBansal** [svermeulen/vim-yoink#22]
```
map <C-p> o <ESC>"+P
nmap P <plug>(YoinkPaste_P)

```
I have this in ~/.vimrc to copy from system clipboard directly, but indentation is not correct whilst using Yoink i.e. mapping P in this case.

**Comment by svermeulen** [comment]
Are you setting a value for `g:yoinkAutoFormatPaste` ?

**Comment by TanishBansal** [comment]
After adding `let g:yoinkAutoFormatPaste='1'` it works in some cases but not all, When not used the indentation is correct for the cases where it's wrong using `let g:yoinkAutoFormatPaste='1'` and vice-versa.

**Comment by svermeulen** [comment]
Can you elaborate more on what you mean by 'not correct'?  You mean the indentation is different from the original text that was copied?  And different from using `<c-p>` like you have there?  When `g:yoinkAutoFormatPaste` is set to `0`, then it should behave the same as `P`.  Also, can you confirm this behaviour with a vim config that only contains `vim-yoink` to eliminate the possibility that another plugin is affecting behaviour?

**Comment by zlksnk** [comment]
@TanishBansal it would be great if you can supply some examples with before/after so we can reproduce it at our side :)

**Comment by svermeulen** [comment]
Closing for now until more info is added
