### ISSUE TITLE
Detected both cutlass and yoink installed - however g:yoinkIncludeDeleteOperations is set to 0.

### ISSUE THREAD

**Issue by kareltucek** [svermeulen/vim-yoink#29]
Hi!

I seem to be somewhat confused. Long story short, It seems like g:yoinkSyncNumberedRegisters negates effect of g:yoinkIncludeDeleteOperations, which in turn leads to  `Detected both cutlass and yoink installed - however g:yoinkIncludeDeleteOperations is set to 0.` error.

I have cutlas with yoink installed alongside, with this config:

```
"map yank "ring" to [p ]p
nmap [p <plug>(YoinkPostPasteSwapBack)
nmap ]p <plug>(YoinkPostPasteSwapForward)
nmap p <plug>(YoinkPaste_p)
nmap P <plug>(YoinkPaste_P)

let g:yoinkIncludeDeleteOperations = 0
let g:yoinkSyncNumberedRegisters = 1

"map x to 'cut'
nnoremap x d
xnoremap x d
nnoremap xx dd
nnoremap X D
```

I.e., I expect only `x` and `y` to go into yank history. This config seems to work, but throws error .

Testing scenario:
```
a
b
c
d
```
Sequence `normal ggyyjyyjyyjxx<Esc>:reg`.

Expected result: `d` in `1` and `"` register.

Actual:
```
let g:yoinkIncludeDeleteOperations = 0
let g:yoinkSyncNumberedRegisters = 1
  l  ""   d^J
  l  "0   c^J
  l  "1   d^J
  l  "2   b^J
```

```
let g:yoinkIncludeDeleteOperations = 1
let g:yoinkSyncNumberedRegisters = 1
  l  ""   c^J
  l  "0   c^J
  l  "1   c^J
  l  "2   b^J
  l  "3   a^J
```

```
let g:yoinkIncludeDeleteOperations = 1
let g:yoinkSyncNumberedRegisters = 0
  l  ""   d^J
  l  "0   c^J
  l  "1   d^J
  l  "2   c^J
```

I.e., the first (and the only one) of the three configs seemsto yield requested behaviour, yet refuses to start without an error.

Question is: am I missing something? If this is expected behaviour, how do I make the error go away properly? (I mean, yeah, I have removed the lines from the plugin, but that is not very persistent. I can also fork the repo and redirect the PlugInstall, but that does not sound right either.)

**Comment by svermeulen** [comment]
By setting `yoinkIncludeDeleteOperations` to `1`, this will do a better job including your "cut" operations (via `x` mapping) in the yank history.

Given the text:

```
a
b
c
d
e
f
g
h
i
```

If you enable `let g:yoinkIncludeDeleteOperations = 1` then execute `normal ggyljyljyljxljxljxlj` then execute `:reg` or `:Yanks` you should see a,b,c,d,e,f, etc.  which is not the case when `let g:yoinkIncludeDeleteOperations = 0`

**Comment by kareltucek** [comment]
I see. With `xl`, the thing works just as you suggest. 

But when I replace `xl`s with `xx`s, I don't see the last 'cutted' line. However I do see the second last. 

I.e., with
```
let g:yoinkIncludeDeleteOperations = 1
let g:yoinkSyncNumberedRegisters = 1

nnoremap x d
xnoremap x d
nnoremap xx dd
nnoremap X D
```

and `normal ggyljyljyljxxxxxx`, I see:
```
:reg
Type Name Content
  l  ""   e^J
  c  "0   c
  l  "1   e^J
  l  "2   d^J
  c  "3   c
  c  "4   b
  c  "5   a
```
(`f^J` is missing altogether.)

(Tested once more with all plugins disabled except your subversive, yoink and cutlass. Same result.)

**Comment by svermeulen** [comment]
Ok I didn't realize that `dd` was making a difference here.  I have now reproduced some of the strangeness you're referring to.

**Comment by svermeulen** [comment]
If you stop using `yoinkSyncNumberedRegisters` can you still reproduce any issues?  I think that may be related to this problem.  It might be fighting with vim to use the '1' register which vim uses for delete operations.

**Comment by svermeulen** [comment]
Also you can disregard the above mentioned commit (78ea90b) since that was a failed idea

**Comment by kareltucek** [comment]
> If you stop using yoinkSyncNumberedRegisters can you still reproduce any issues?

Well... with includeDeleteOperations 1 and syncNumberedRegisters 0:

- `xx` end up in `"` and in `1` registers immediately (and from there gets shifted as expected).
- `xl` ends up only in `"`, and does not get moved into `1` on further delete operations.

(Not sure whether the first behaviour is correct by definition. Second one does not seem so.)

**Comment by svermeulen** [comment]
So vim has its own way of updating the numbered registers independently from vim-yoink.  It has some weird behaviour, like treating multi-line deletes differently than single line deletes, and also only storing deletes in the numbered registers instead of both yanks and deletes.  Described in more detail here:  http://vimcasts.org/blog/2013/11/registers-the-good-the-bad-and-the-ugly-parts/

It would be nice if this `yoinkSyncNumberedRegisters` yoink feature overrode that weird default behaviour from vim and instead just stored all cut/yank history there.

I think the issue here is that for whatever reason, when we set a value for register '1', this can also clobber the default register with the same content.  So I've added a fix for this in branch `sverm/NumberedRegistersFix` where it now will restore default register to what it was before this numbered register logic.  Can you try using that branch and report back if it still has any issues?

**Comment by kareltucek** [comment]
Alright, I didn't realize that small deletion register was in play here.

>  Can you try using that branch and report back if it still has any issues?

With pleasure! So far, it seems to behave consistently.

I am just wondering about one thing - I would find it more intuitive if meaning of `"` and `0` registers remained separate (i.e., `0` would always contain last yank). Now, `0` is unified with `"`. Is there a simple way to achieve that? (If not, it's fine, I can get used to current behavior.)

**Comment by svermeulen** [comment]
I agree that it would be nice if '0' remained for yanks only.  I assumed that was already the case until your comment.

I can't figure out a way to do that though.  Using your example vimrc, for whatever reason, when I set a value for the `0` register explicitly with `setreg`, this automatically sets a value for `"`, and similarly when setting a value for `"`

**Comment by kareltucek** [comment]
So... I did some digging. 

Long story short, unnamed register is just a pointer to the last used register (although restricted to specific actions). (I was not aware of that.) In case of read action, the pointed register is simply read. In case of write actions, content is written into `"0` and unnamed is pointed to the `"0`. (In code, unnamed is referred to as `y_previous`, while future-action register is pointed by `y_current`.)

This means that in case of delete operations, the text is written either to `"1` or to `"-`, and unnamed is only set to point to this register. In case of yank, the same holds for `"0`.

Sources:
- someone has already ran into this problem here - https://vi.stackexchange.com/questions/20005/how-to-use-register-in-a-script-without-side-effect . (I am not aware of any solution in neovim. Regarding the fix introduced last year in classic vim, I find it sort of hackish.)
- http://vimdoc.sourceforge.net/htmldoc/change.html#registers explicitly sais:
``` 
Vim uses the contents of the unnamed register for any put command (p or P)
which does not specify a register.  Additionally you can access it with the
name '"''.  This means you have to type two double quotes.  Writing to the ""
register writes to register "0.
```
- in classic vim, the key line is this: https://github.com/vim/vim/blob/f2a8bafa4b815e5b4e50a25c2b3a8a24fbe8aa11/src/register.c#L219 Indeed both yank code and `setreg`command lead there.

----------------------------

Anyway, I see two roads going from here:

- one, redefine the behaviour so that `"1` is written immediately as part of the action itself (no matter whether delete or yank), rather than to wait until next action. 

- second - simply forget about `"0`.

Thinking about it again in the light of above findings, i am quite happy with the second option (that is, current state of affairs with the `sverm/NumberedRegistersFix` branch). Therefore I guess we can close this (?). 

In any case, thanks for your time and all your published code!

**Comment by svermeulen** [comment]
Sounds good!  Thanks for your help on this

**Comment by svermeulen** [comment]
I've now merged that change into master btw
