### ISSUE TITLE
feature comparison to extract.vim ?

### ISSUE THREAD

**Issue by davidosomething** [svermeulen/vim-yoink#4]
Not sure if you found it, but here's another plugin I've been using https://github.com/cyansprite/Extract
Wondering what differences you're aiming to add

**Comment by svermeulen** [comment]
I actually didn't find that one.  Before I created this I was using mini-yank or easyclip for this kind of functionality.  I haven't used Extract so not sure what's different.  From skimming the readme, not integrating with autocomplete would be one difference.  The swapping functionality sounds more or less the same.
