### ISSUE TITLE
bug: Cannot directly paste after delete.

### ISSUE THREAD

**Issue by chenzhihuai1990** [svermeulen/vim-yoink#8]
When I type command `dp`, only delete action works but paste action doesn't.
It since the `v:register` change to `_` after the `d` action. Maybe, the code I found in easyclip should be added:
```
if reg ==# '_'
  let reg = EasyClip#GetDefaultReg()
end
```

**Comment by svermeulen** [comment]
Yep, this is a bug in vim.  I brought this up to Bram himself and learned that he doesn't intend to fix it.   So we should add the same workaround that easy clip uses.

**Comment by svermeulen** [comment]
Fixed.  Thanks for pointing this out
