### ISSUE TITLE
Ctrl-N and ctrl-p after paste does not work.

### ISSUE THREAD

**Issue by jdhao** [svermeulen/vim-yoink#9]
I am using neovim (version 0.3.4) on Windows 10 and `Ctrl-N`, `Ctrl-P` right after paste does not work. The message I got is:

> Last action was not paste - swap ignored

My setting for yoink is:

```
    " it seems that ctrl-n and ctrl-p does not work on neovim
    nmap <c-n> <plug>(YoinkPostPasteSwapBack)
    nmap <c-p> <plug>(YoinkPostPasteSwapForward)

    nmap p <plug>(YoinkPaste_p)
    nmap P <plug>(YoinkPaste_P)

    " cycle the yank stack with the following mappings
    nmap [y <plug>(YoinkRotateBack)
    nmap ]y <plug>(YoinkRotateForward)

    " not change the cursor position
    " nmap y <plug>(YoinkYankPreserveCursorPosition)
    " xmap y <plug>(YoinkYankPreserveCursorPosition)

    " move cursor to end of paste after multiline paste
    let g:yoinkMoveCursorToEndOfPaste = 1

    " record yanks in system clipboard
    let g:yoinkSyncSystemClipboardOnFocus = 1
```
I have also noticed with this plugin enabled, the cursor will be put at the end of the pasted text instead of the first character of the pasted text.

The command `verbose nmap p` shows:

```
n p <Plug>(YoinkPaste_p) 
Last set from ~\AppData\Local\nvim\init.vim
```

**Comment by svermeulen** [comment]
You need to either leave `g:yoinkMoveCursorToEndOfPaste` unset or set it to zero, if you don't want the cursor to move when pasting.  Yoink should match vim defaults by default.

I can't reproduce the problem with `<c-n>` and `<c-p>` though unfortunately.  I use neovim also and it works fine for me.  Can you try again with a minimal .vimrc?  I just tried what you provided with only yoink installed and it worked fine

**Comment by jdhao** [comment]
If I use the following  minimal `init.vim`:

```
if has('win32')
    let g:PLUG_HOME="~/AppData/Local/nvim/plugged"
else
    let g:PLUG_HOME="~/.local/share/nvim/plugged"
endif

call plug#begin(g:PLUG_HOME)

    Plug 'svermeulen/vim-yoink'

call plug#end()

nmap <c-n> <plug>(YoinkPostPasteSwapBack)
nmap <c-p> <plug>(YoinkPostPasteSwapForward)

nmap p <plug>(YoinkPaste_p)
nmap P <plug>(YoinkPaste_P)
```

`<C-N>` and `<C-P>` works as expected.  Maybe there is some settings or plugins interfere with this behavior? But `verbose nmap <c-n>`, `verbose nmap <c-p>` and `verbose namp p` show that the mappings are set from Yoink. I am not sure how do I debug further. Any hints?

**Comment by svermeulen** [comment]
What that message means is that the value for `b:changedtick` has changed since the past occurred.  Do you have any autocommands or something that run when changes occur to do things like formatting ?  If so that could cause it.  What happens when you hit undo?  Does it go back to before the past occurred?

Other than that, I'd recommend narrowing it down by slowly adding the other parts of your config until the issue occurs again if that's possible

**Comment by jdhao** [comment]
Thanks for the hint! I have found the reason! 

There is a plugin [vim-auto-save](https://github.com/907th/vim-auto-save) which I use to autosave my file once leave insert mode. So after paste, a save operation is automatically applied to the file.

 If I turn off this plugin, I can use `<c-n>` and `<c-p>` without problem.

**Comment by svermeulen** [comment]
No problem, glad you fixed it

**Comment by mottalrd** [comment]
Thank you @jdhao , I had the same issue. I am not happy to give up on vim-auto-save so for now I am happy to just use `[y` to find the yank I need. Is there any way to do :Yanks and then pick one?
